print("For which event you want to get a reminder?")
print("Here we've a list for bunch of events.")
print("1. New year's Eve\n")
print("2. Guru Govind Singh Jayanti\n")
print("3. Epiphany\n")
print("4. Orthodox Christmas Day\n")
print("5. Stephen Foster Memorial Day\n")
print("6. Orthodox New Year\n")